import { Category, Medicine } from "@/types/categories.types";

export const categories: Category[] = [
  {
    id: 1,
    name: "Daily Essentials",
    description: "Vitamins, pain relief, hygiene",
  },
  {
    id: 2,
    name: "Personal Care",
    description: "Skin care, hygiene, beauty",
  },
  {
    id: 3,
    name: "Cold & Flu Medicine",
    description: "Flu, cough, sore throat",
  },
  {
    id: 4,
    name: "First Aid",
    description: "Cuts, burns, injuries",
  },
  {
    id: 5,
    name: "Vitamins & Supplements",
    description: "Nutrition & immune support",
  },
];

export const medicines: Medicine[] = [
  {
    id: "m1",
    name: "Paracetamol 500mg",
    description: "Pain and fever relief tablets",
    longDescription:
      "Paracetamol 500mg is used to relieve mild to moderate pain including headaches, toothache, and muscle aches.",
    price: 4.2,
    discount: 5,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 1,
    stock: 120,
    rating: 4.3,
    salesCount: 540,
    sku: "PARA-500-02",
    isActive: true,
    prescriptionRequired: false,
    form: "Tablet",
    packSize: "20 tablets",
    ingredients: "Paracetamol 500mg per tablet",
    directions: "Take 1–2 tablets every 4–6 hours.",
    warnings: "Do not exceed recommended dose.",
    storage: "Store below 25°C.",
  },
  {
    id: "m2",
    name: "Ibuprofen 400mg",
    description: "Anti-inflammatory pain reliever",
    longDescription:
      "Used for reducing inflammation and relieving pain such as back pain and menstrual cramps.",
    price: 6.5,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 1,
    stock: 80,
    rating: 4.5,
    salesCount: 320,
    sku: "IBU-400-01",
    isActive: true,
    prescriptionRequired: false,
    form: "Tablet",
    packSize: "24 tablets",
    ingredients: "Ibuprofen 400mg",
    directions: "Take 1 tablet every 6–8 hours.",
    warnings: "Take with food.",
    storage: "Store in a cool place.",
  },
  {
    id: "m3",
    name: "Amoxicillin 500mg",
    description: "Antibiotic capsules",
    longDescription:
      "Amoxicillin is used to treat bacterial infections including chest, throat, and ear infections.",
    price: 12.0,
    discount: 10,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 2,
    stock: 45,
    rating: 4.6,
    salesCount: 210,
    sku: "AMOX-500-01",
    isActive: true,
    prescriptionRequired: true,
    form: "Capsule",
    packSize: "16 capsules",
    ingredients: "Amoxicillin 500mg",
    directions: "Take as prescribed by doctor.",
    warnings: "Complete full course.",
    storage: "Store below 25°C.",
  },
  {
    id: "m4",
    name: "Vitamin C 1000mg",
    description: "Immune system support",
    longDescription:
      "Vitamin C helps boost immune function and supports overall health.",
    price: 8.3,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 3,
    stock: 150,
    rating: 4.4,
    salesCount: 410,
    sku: "VITC-1000-01",
    isActive: true,
    prescriptionRequired: false,
    form: "Tablet",
    packSize: "30 tablets",
    ingredients: "Vitamin C 1000mg",
    directions: "Take 1 tablet daily.",
    warnings: "Do not exceed daily dose.",
    storage: "Store in dry place.",
  },
  {
    id: "m5",
    name: "Cough Syrup",
    description: "Relieves dry and chesty cough",
    longDescription: "Effective relief for cough and throat irritation.",
    price: 7.9,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 4,
    stock: 60,
    rating: 4.2,
    salesCount: 290,
    sku: "COUGH-100",
    isActive: true,
    prescriptionRequired: false,
    form: "Syrup",
    packSize: "100ml",
    ingredients: "Dextromethorphan",
    directions: "Take 10ml 3 times daily.",
    warnings: "Not for children under 6.",
    storage: "Store below 25°C.",
  },
  {
    id: "m6",
    name: "Allergy Relief Tablets",
    description: "Antihistamine for allergies",
    longDescription: "Provides relief from hay fever and allergy symptoms.",
    price: 5.5,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 5,
    stock: 90,
    rating: 4.1,
    salesCount: 180,
    sku: "ALLER-10",
    isActive: true,
    prescriptionRequired: false,
    form: "Tablet",
    packSize: "10 tablets",
    ingredients: "Loratadine 10mg",
    directions: "Take 1 tablet daily.",
    warnings: "May cause drowsiness.",
    storage: "Keep in cool place.",
  },
  {
    id: "m7",
    name: "Omeprazole 20mg",
    description: "Reduces stomach acid",
    longDescription: "Used to treat acid reflux and heartburn.",
    price: 9.8,
    discount: 5,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 6,
    stock: 70,
    rating: 4.4,
    salesCount: 230,
    sku: "OMEP-20",
    isActive: true,
    prescriptionRequired: false,
    form: "Capsule",
    packSize: "14 capsules",
    ingredients: "Omeprazole 20mg",
    directions: "Take 1 capsule daily before meals.",
    warnings: "Consult doctor if symptoms persist.",
    storage: "Store below 30°C.",
  },
  {
    id: "m8",
    name: "Insulin Injection",
    description: "Blood sugar control",
    longDescription: "Insulin injection for managing diabetes.",
    price: 25.0,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 3,
    stock: 25,
    rating: 4.7,
    salesCount: 95,
    sku: "INS-100",
    isActive: true,
    prescriptionRequired: true,
    form: "Injection",
    packSize: "10ml vial",
    ingredients: "Human insulin",
    directions: "Use as prescribed.",
    warnings: "Keep refrigerated.",
    storage: "Store in fridge (2–8°C).",
  },
  {
    id: "m9",
    name: "Multivitamin Capsules",
    description: "Daily nutritional supplement",
    longDescription: "Supports general health and energy levels.",
    price: 11.5,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 3,
    stock: 140,
    rating: 4.5,
    salesCount: 360,
    sku: "MULTI-30",
    isActive: true,
    prescriptionRequired: false,
    form: "Capsule",
    packSize: "30 capsules",
    ingredients: "Vitamins & Minerals",
    directions: "Take 1 capsule daily.",
    warnings: "Do not exceed recommended dose.",
    storage: "Store in dry place.",
  },
  {
    id: "m10",
    name: "Nasal Spray",
    description: "Relieves nasal congestion",
    longDescription: "Fast relief from blocked nose due to cold or allergies.",
    price: 6.8,
    discount: 0,
    imageUrl: "/patient/Pain Relief-X.png",
    images: ["/patient/Pain Relief-X.png"],
    categoryId: 4,
    stock: 55,
    rating: 4.2,
    salesCount: 150,
    sku: "NASAL-15",
    isActive: true,
    prescriptionRequired: false,
    form: "Spray",
    packSize: "15ml",
    ingredients: "Xylometazoline",
    directions: "1 spray per nostril twice daily.",
    warnings: "Do not use for more than 7 days.",
    storage: "Store below 25°C.",
  },
];
