import { Pharmacy } from "@/types/pharmacyTypes";

export const NEARBY_PHARMACIES: Pharmacy[] = [
  {
    id: "PH001",
    name: "City Pharmacy",
    address: "Ibn Abi Dhiaf St, Tunis 1002, Tunisia",
    distance: "0.8 km from you",
    distanceInKm: 0.8,
    rating: 4.8,
    reviewCount: 324,
    deliveryFee: 0,
    imageUrl: "/pharmacies/city-pharmacy-1.jpg",
    isOpen: true,
    openingHours: "Open: 8:00 AM - 10:00 PM",
  },
  {
    id: "PH002",
    name: "City Pharmacy",
    address: "Avenue Habib Bourguiba, Tunis 1000, Tunisia",
    distance: "1.5 km from you",
    distanceInKm: 1.5,
    rating: 4.6,
    reviewCount: 289,
    deliveryFee: 0,
    imageUrl: "/pharmacies/city-pharmacy-2.jpg",
    isOpen: true,
    openingHours: "Open: 8:00 AM - 9:00 PM",
  },
  {
    id: "PH003",
    name: "City Pharmacy",
    address: "Rue de Marseille, Tunis 1001, Tunisia",
    distance: "2.0 km from you",
    distanceInKm: 2.0,
    rating: 4.7,
    reviewCount: 412,
    deliveryFee: 0,
    imageUrl: "/pharmacies/city-pharmacy-3.jpg",
    isOpen: true,
    openingHours: "Open: 24 Hours",
  },
  {
    id: "PH004",
    name: "City Pharmacy",
    address: "Avenue de la Liberté, Tunis 1002, Tunisia",
    distance: "2.5 km from you",
    distanceInKm: 2.5,
    rating: 4.5,
    reviewCount: 198,
    deliveryFee: 0,
    imageUrl: "/pharmacies/city-pharmacy-4.jpg",
    isOpen: true,
    openingHours: "Open: 8:00 AM - 8:00 PM",
  },
  {
    id: "PH005",
    name: "City Pharmacy",
    address: "Rue Charles de Gaulle, Tunis 1000, Tunisia",
    distance: "3.0 km from you",
    distanceInKm: 3.0,
    rating: 4.9,
    reviewCount: 567,
    deliveryFee: 0,
    imageUrl: "/pharmacies/city-pharmacy-5.jpg",
    isOpen: true,
    openingHours: "Open: 7:00 AM - 11:00 PM",
  },
];
