import { InventoryItem, OrderRow } from "@/types/pharmacyTypes";

export const inventoryData: InventoryItem[] = [
  {
    id: "P0001",
    medicineName: "Paracetamol 500mg",
    brand: "GSK",
    manufacturer: "GlaxoSmithKline",
    category: "pain_relief",
    stock: 30,
    minStock: 10,
    status: "in",
    batchNumber: "PAR-2024-01",
    expiryDate: "2026-02-08",
    prescriptionRequired: false,
    purchasePrice: 1.5,
    sellingPrice: 2.0,
    imageUrl: "/paracetamol.png",
    usageNotes: ["One tablet every 4–6 hours"],
  },

  {
    id: "P0002",
    medicineName: "Atorvastatin 20mg",
    brand: "Pfizer",
    manufacturer: "Pfizer",
    category: "heart",
    stock: 20,
    minStock: 8,
    status: "in",
    batchNumber: "ATO-2024-02",
    expiryDate: "2027-05-15",
    prescriptionRequired: true,
    purchasePrice: 2.5,
    sellingPrice: 3.8,
    imageUrl: "/atorvastatin.png",
    usageNotes: ["Take once daily"],
  },

  {
    id: "P0003",
    medicineName: "Vitamin D3 1000 IU",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    category: "supplements",
    stock: 25,
    minStock: 10,
    status: "in",
    batchNumber: "VIT-2024-03",
    expiryDate: "2027-12-15",
    prescriptionRequired: false,
    purchasePrice: 1.8,
    sellingPrice: 2.5,
    imageUrl: "/vitamin-d3.png",
    usageNotes: ["One capsule daily"],
  },

  {
    id: "P0004",
    medicineName: "Aspirin 100mg",
    brand: "Bayer",
    manufacturer: "Bayer",
    category: "pain_relief",
    stock: 12,
    minStock: 10,
    status: "low",
    batchNumber: "ASP-2024-04",
    expiryDate: "2027-08-10",
    prescriptionRequired: false,
    purchasePrice: 1.2,
    sellingPrice: 1.8,
    imageUrl: "/aspirin.png",
    usageNotes: ["Take with food"],
  },

  {
    id: "P0005",
    medicineName: "Amoxicillin 500mg",
    brand: "Sandoz",
    manufacturer: "Sandoz",
    category: "antibiotics",
    stock: 18,
    minStock: 8,
    status: "in",
    batchNumber: "AMO-2024-05",
    expiryDate: "2026-11-20",
    prescriptionRequired: true,
    purchasePrice: 2.0,
    sellingPrice: 3.2,
    imageUrl: "/amoxicillin.png",
    usageNotes: ["Complete full course"],
  },

  {
    id: "P0006",
    medicineName: "Ibuprofen 400mg",
    brand: "Advil",
    manufacturer: "Pfizer",
    category: "pain_relief",
    stock: 15,
    minStock: 7,
    status: "in",
    batchNumber: "IBU-2024-06",
    expiryDate: "2026-09-30",
    prescriptionRequired: false,
    purchasePrice: 1.3,
    sellingPrice: 2.1,
    imageUrl: "/ibuprofen.png",
    usageNotes: ["Take after meals"],
  },
];

export const ORDERS: OrderRow[] = [
  // ===== PARACETAMOL (6 orders)
  {
    id: "O0001",
    inventoryId: "P0001",
    customer: "Eman Mohammad",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "11 Feb",
    status: "Delivered",
  },
  {
    id: "O0002",
    inventoryId: "P0001",
    customer: "Ahmad Ali",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "10 Feb",
    status: "Delivered",
  },
  {
    id: "O0003",
    inventoryId: "P0001",
    customer: "Sara Hassan",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "09 Feb",
    status: "Pending",
  },
  {
    id: "O0004",
    inventoryId: "P0001",
    customer: "Mona Khaled",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "08 Feb",
    status: "Delivered",
  },
  {
    id: "O0005",
    inventoryId: "P0001",
    customer: "Yousef Omar",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "07 Feb",
    status: "Delivered",
  },
  {
    id: "O0006",
    inventoryId: "P0001",
    customer: "Lina Ahmad",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "06 Feb",
    status: "Delivered",
  },

  // ===== ATORVASTATIN (4 orders)
  {
    id: "O0007",
    inventoryId: "P0002",
    customer: "Khaled Sami",
    medicine: "Atorvastatin 20mg",
    total: "30.00$",
    date: "11 Feb",
    status: "Delivered",
  },
  {
    id: "O0008",
    inventoryId: "P0002",
    customer: "Noor Adel",
    medicine: "Atorvastatin 20mg",
    total: "30.00$",
    date: "10 Feb",
    status: "Delivered",
  },
  {
    id: "O0009",
    inventoryId: "P0002",
    customer: "Rana Yassin",
    medicine: "Atorvastatin 20mg",
    total: "30.00$",
    date: "09 Feb",
    status: "Pending",
  },
  {
    id: "O0010",
    inventoryId: "P0002",
    customer: "Huda Karim",
    medicine: "Atorvastatin 20mg",
    total: "30.00$",
    date: "08 Feb",
    status: "Delivered",
  },

  // ===== VITAMIN D3 (3 orders)
  {
    id: "O0011",
    inventoryId: "P0003",
    customer: "Omar Nabil",
    medicine: "Vitamin D3 1000 IU",
    total: "18.00$",
    date: "11 Feb",
    status: "Delivered",
  },
  {
    id: "O0012",
    inventoryId: "P0003",
    customer: "Mariam Said",
    medicine: "Vitamin D3 1000 IU",
    total: "18.00$",
    date: "10 Feb",
    status: "Pending",
  },
  {
    id: "O0013",
    inventoryId: "P0003",
    customer: "Samir Fadi",
    medicine: "Vitamin D3 1000 IU",
    total: "18.00$",
    date: "09 Feb",
    status: "Delivered",
  },

  // ===== ASPIRIN (2 orders)
  {
    id: "O0014",
    inventoryId: "P0004",
    customer: "Hana Mahmoud",
    medicine: "Aspirin 100mg",
    total: "12.00$",
    date: "10 Feb",
    status: "Delivered",
  },
  {
    id: "O0015",
    inventoryId: "P0004",
    customer: "Mahmoud Tarek",
    medicine: "Aspirin 100mg",
    total: "12.00$",
    date: "08 Feb",
    status: "Pending",
  },

  // ===== AMOXICILLIN (2 orders)
  {
    id: "O0016",
    inventoryId: "P0005",
    customer: "Nour Ali",
    medicine: "Amoxicillin 500mg",
    total: "25.00$",
    date: "07 Feb",
    status: "Delivered",
  },
  {
    id: "O0017",
    inventoryId: "P0005",
    customer: "Yara Sami",
    medicine: "Amoxicillin 500mg",
    total: "25.00$",
    date: "06 Feb",
    status: "Delivered",
  },

  // ===== IBUPROFEN (1 order)
  {
    id: "O0018",
    inventoryId: "P0006",
    customer: "Ziad Nasser",
    medicine: "Ibuprofen 400mg",
    total: "15.00$",
    date: "05 Feb",
    status: "Pending",
  },
];
