import { InventoryItem, OrderRow } from "@/types/pharmacyTypes";

export const inventoryData: InventoryItem[] = [
  {
    id: "P0001",
    medicineName: "Paracetamol 500mg",
    brand: "GSK",
    manufacturer: "GlaxoSmithKline",
    category: "pain_relief",
    stock: 12,
    minStock: 10,
    status: "in",
    batchNumber: "PAR-2024-01",
    expiryDate: "2026-02-08",
    prescriptionRequired: false,
    purchasePrice: 1.5,
    sellingPrice: 2.0,
    imageUrl: "/paracetamol.png",
    usageNotes: ["One tablet every 4–6 hours"],
  },

  {
    id: "P0002",
    medicineName: "Atorvastatin 20mg",
    brand: "Pfizer",
    manufacturer: "Pfizer",
    category: "heart",
    stock: 10,
    minStock: 8,
    status: "in",
    batchNumber: "ATO-2024-02",
    expiryDate: "2027-05-15",
    prescriptionRequired: true,
    purchasePrice: 2.5,
    sellingPrice: 3.8,
    imageUrl: "/atorvastatin.png",
    usageNotes: ["Take once daily"],
  },

  {
    id: "P0003",
    medicineName: "Vitamin D3 1000 IU",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    category: "supplements",
    stock: 8,
    minStock: 10,
    status: "in",
    batchNumber: "VIT-2024-03",
    expiryDate: "2027-12-15",
    prescriptionRequired: false,
    purchasePrice: 1.8,
    sellingPrice: 2.5,
    imageUrl: "/vitamin-d3.png",
    usageNotes: ["One capsule daily"],
  },

  {
    id: "P0004",
    medicineName: "Aspirin 100mg",
    brand: "Bayer",
    manufacturer: "Bayer",
    category: "pain_relief",
    stock: 12,
    minStock: 10,
    status: "low",
    batchNumber: "ASP-2024-04",
    expiryDate: "2027-08-10",
    prescriptionRequired: false,
    purchasePrice: 1.2,
    sellingPrice: 1.8,
    imageUrl: "/aspirin.png",
    usageNotes: ["Take with food"],
  },

  {
    id: "P0005",
    medicineName: "Amoxicillin 500mg",
    brand: "Sandoz",
    manufacturer: "Sandoz",
    category: "antibiotics",
    stock: 0,
    minStock: 8,
    status: "in",
    batchNumber: "AMO-2024-05",
    expiryDate: "2026-11-20",
    prescriptionRequired: true,
    purchasePrice: 2.0,
    sellingPrice: 3.2,
    imageUrl: "/amoxicillin.png",
    usageNotes: ["Complete full course"],
  },

  {
    id: "P0006",
    medicineName: "Ibuprofen 400mg",
    brand: "Advil",
    manufacturer: "Pfizer",
    category: "pain_relief",
    stock: 15,
    minStock: 7,
    status: "in",
    batchNumber: "IBU-2024-06",
    expiryDate: "2026-09-30",
    prescriptionRequired: false,
    purchasePrice: 1.3,
    sellingPrice: 2.1,
    imageUrl: "/ibuprofen.png",
    usageNotes: ["Take after meals"],
  },
];

export const ORDERS: OrderRow[] = [
  {
    id: "O0001",
    customer: "Eman Mohammad",
    items: [
      { inventoryId: "P0001", quantity: 2, unitPrice: 11.5 },
      { inventoryId: "P0003", quantity: 1, unitPrice: 18 },
    ],
    total: 41,
    date: "11 Feb",
    status: "Delivered",
  },

  {
    id: "O0002",
    customer: "Ahmad Ali",
    items: [{ inventoryId: "P0001", quantity: 1, unitPrice: 11.5 }],
    total: 11.5,
    date: "10 Feb",
    status: "Delivered",
  },

  {
    id: "O0003",
    customer: "Sara Hassan",
    items: [
      { inventoryId: "P0001", quantity: 1, unitPrice: 11.5 },
      { inventoryId: "P0004", quantity: 2, unitPrice: 6 },
    ],
    total: 23.5,
    date: "09 Feb",
    status: "Pending",
  },

  {
    id: "O0004",
    customer: "Mona Khaled",
    items: [{ inventoryId: "P0002", quantity: 1, unitPrice: 30 }],
    total: 30,
    date: "08 Feb",
    status: "Delivered",
  },

  {
    id: "O0005",
    customer: "Yousef Omar",
    items: [
      { inventoryId: "P0003", quantity: 2, unitPrice: 18 },
      { inventoryId: "P0006", quantity: 1, unitPrice: 15 },
    ],
    total: 51,
    date: "07 Feb",
    status: "Delivered",
  },

  {
    id: "O0006",
    customer: "Lina Ahmad",
    items: [
      { inventoryId: "P0005", quantity: 1, unitPrice: 25 },
      { inventoryId: "P0001", quantity: 1, unitPrice: 11.5 },
      { inventoryId: "P0004", quantity: 1, unitPrice: 6 },
    ],
    total: 42.5,
    date: "06 Feb",
    status: "New",
  },

  {
    id: "O0007",
    customer: "Khaled Sami",
    items: [
      { inventoryId: "P0002", quantity: 1, unitPrice: 30 },
      { inventoryId: "P0003", quantity: 1, unitPrice: 18 },
    ],
    total: 48,
    date: "05 Feb",
    status: "Delivered",
  },

  {
    id: "O0008",
    customer: "Noor Adel",
    items: [{ inventoryId: "P0006", quantity: 2, unitPrice: 15 }],
    total: 30,
    date: "04 Feb",
    status: "Cancelled",
  },

  {
    id: "O0009",
    customer: "Rana Yassin",
    items: [
      { inventoryId: "P0003", quantity: 1, unitPrice: 18 },
      { inventoryId: "P0001", quantity: 1, unitPrice: 11.5 },
    ],
    total: 29.5,
    date: "03 Feb",
    status: "Pending",
  },

  {
    id: "O0010",
    customer: "Huda Karim",
    items: [{ inventoryId: "P0004", quantity: 3, unitPrice: 6 }],
    total: 18,
    date: "02 Feb",
    status: "Delivered",
  },
];
