import { InventoryRow } from "../inventory/InventoryTable";

export const inventoryData: InventoryRow[] = [
  {
    id: "P0001",
    medicine: "Panadol",
    brand: "GSK",
    stock: "30 pacs",
    expiration: "12 months",
    status: "in",
  },
  {
    id: "P0002",
    medicine: "Aspirin",
    brand: "Bayer",
    stock: "12 pacs",
    expiration: "8 months",
    status: "low",
  },
  {
    id: "P0003",
    medicine: "Amoxicillin",
    brand: "Pfizer",
    stock: "0 pacs",
    expiration: "—",
    status: "out",
  },
  {
    id: "P0004",
    medicine: "Ibuprofen",
    brand: "Abbott",
    stock: "20 pacs",
    expiration: "14 months",
    status: "in",
  },
  {
    id: "P0005",
    medicine: "Vitamin C",
    brand: "Nature Made",
    stock: "7 pacs",
    expiration: "6 months",
    status: "low",
  },
  {
    id: "P0006",
    medicine: "Cough Syrup",
    brand: "Vicks",
    stock: "0 pacs",
    expiration: "—",
    status: "out",
  },
  {
    id: "P0007",
    medicine: "Paracetamol",
    brand: "Sanofi",
    stock: "40 pacs",
    expiration: "18 months",
    status: "in",
  },
  {
    id: "P0008",
    medicine: "Antacid",
    brand: "Gaviscon",
    stock: "9 pacs",
    expiration: "5 months",
    status: "low",
  },
  {
    id: "P0009",
    medicine: "Insulin",
    brand: "Novo Nordisk",
    stock: "3 pacs",
    expiration: "2 months",
    status: "low",
  },
  {
    id: "P0010",
    medicine: "Eye Drops",
    brand: "Alcon",
    stock: "15 pacs",
    expiration: "10 months",
    status: "in",
  },
];
