import { InventoryRow, OrderRow } from "./types";

export const inventoryData: InventoryRow[] = [
  {
    id: "P0001",
    medicine: "Panadol",
    brand: "GSK",
    stock: "30 pacs",
    expiration: "12 months",
    status: "in",
    category: "pain_relief",
  },
  {
    id: "P0002",
    medicine: "Aspirin",
    brand: "Bayer",
    stock: "12 pacs",
    expiration: "8 months",
    status: "low",
    category: "pain_relief",
  },
  {
    id: "P0003",
    medicine: "Amoxicillin",
    brand: "Pfizer",
    stock: "0 pacs",
    expiration: "—",
    status: "out",
    category: "antibiotics",
  },
  {
    id: "P0004",
    medicine: "Ibuprofen",
    brand: "Abbott",
    stock: "20 pacs",
    expiration: "14 months",
    status: "in",
    category: "pain_relief",
  },
  {
    id: "P0005",
    medicine: "Vitamin C",
    brand: "Nature Made",
    stock: "7 pacs",
    expiration: "6 months",
    status: "low",
    category: "vitamins",
  },
  {
    id: "P0006",
    medicine: "Cough Syrup",
    brand: "Vicks",
    stock: "0 pacs",
    expiration: "—",
    status: "out",
    category: "cough_cold",
  },
  {
    id: "P0007",
    medicine: "Paracetamol",
    brand: "Sanofi",
    stock: "40 pacs",
    expiration: "18 months",
    status: "in",
    category: "pain_relief",
  },
  {
    id: "P0008",
    medicine: "Antacid",
    brand: "Gaviscon",
    stock: "9 pacs",
    expiration: "5 months",
    status: "low",
    category: "digestive",
  },
  {
    id: "P0009",
    medicine: "Insulin",
    brand: "Novo Nordisk",
    stock: "3 pacs",
    expiration: "2 months",
    status: "low",
    category: "diabetes",
  },
  {
    id: "P0010",
    medicine: "Eye Drops",
    brand: "Alcon",
    stock: "15 pacs",
    expiration: "10 months",
    status: "in",
    category: "eye_care",
  },
];

export const ORDERS: OrderRow[] = [
  {
    id: "O0001",
    inventoryId: "P0007",
    customer: "Eman Mohammad",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "24 June",
    status: "Delivered",
  },
  {
    id: "O0002",
    inventoryId: "P0007",
    customer: "Eman Mohammad",
    medicine: "Paracetamol 500mg",
    total: "23.00$",
    date: "24 June",
    status: "Delivered",
  },
];
